### PR TITLE
Remove FuzzySharp from PostBuild event in AGS_Engine

### LINKED ISSUE #23: Remove FuzzySharp from the post build event for AGS_Engine
#### Description:

Installer check fails referencing AGS_Engine:
https://github.com/BHoM/MidasCivil_Toolkit/pull/386/checks?check_run_id=29780880215

#### Steps to reproduce:

Run check installer

#### Expected behaviour:

Passing check

#### Test file(s):

BHoMBot

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #23 

### Test files

Installer check

### Changelog

- Removed FuzzySharp reference from PostBuild event on AGS_Engine as that has been migrated to the Search_Engine;

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check core
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check serialisation
@BHoMBot check compliance
@BHoMBot null-handling
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check null-handling

**Review by EmmaSander — COMMENTED** [review]
Has been compiled

**Review by EmmaSander — APPROVED** [review]
Has been compiled

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
