### PR TITLE
Implement changes to the Ground_oM

### LINKED ISSUE #14: Change ContaminantSample read from ERES_RVAL to ERES_RTXT
#### Description:

Change the reading of `ContaminantSample` from `ERES_RVAL` to `ERES_RTXT` - this is because `ERES_RTXT` contains useful information about whether the `Result` is below the detection limit (i.e. < 0,1).

### LINKED ISSUE #15: Downgrade errors for headings not being available to warnings

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM/pull/1626
   
### Issues addressed by this PR

Closes #14 
Closes #15 

### Test files

[#1626-ChangesToContaminantSampleAndResultProperties](https://burohappold.sharepoint.com/:u:/s/BHoM/EY5qP2DpgvdIpmFinZ59PucBXiqfH86BNKhsHAjhvoY-jQ?e=LAwwLx)

### Changelog

- Changed the `ContaminantSample.Result` property to read from `ERES_RTXT` instead of `ERES_RVAL` to capture any instances where the detection limit was not exceeded (i.e. using < )
- Added the `ContaminantSampleResultQuantity` to be read from the units of the result;
- Downgraded from `Error` to `Warning` when the heading within an AGS file is not found.

### CODE REVIEW

**Review by Martian42 — DISMISSED** [review]
Tested functionality with test script using an .ags file with empty GEOL. All option works as intented.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by jtrainor1 — APPROVED** [review]
Reviewed and the changes are working as expected.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Pull request merged**
