### PR TITLE
Add different methods for handling blank GEOL_GEOL

### LINKED ISSUE #12: Read GEOL_GEOL code from description
#### Description:

When GEOL_GEOL is not populated, the `Stratum` does not have a name.

#### Steps to reproduce:

See test file.

#### Expected behaviour:

Take the name from the description is capitals (raise a warning when this is done).

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Engine/pull/3375

### Issues addressed by this PR

Closes #12 

### Test files

https://burohappold.sharepoint.com/:x:/s/BHoM/EYiWcAMZ_jFAl782pP6Pgv8BAGorGhyPFzg3r_3PD6p_ew?e=K8CPRI

### Changelog

- Added `BlankGeologyStrategy` that lets the user select different methods for handling empty GEOL_GEOL fields;
- The `Replace` will replace the blank field with a specific string;
- The `Lexicon` will replace the blank field with the lexicon code (if not empty);
- The `Legend` will replace the blank field with the legend code (if not empty);
- The `Description` will replace the blank field with the capitalised words in the description;

### Additional comments

This will need to wait for the BHoM_Engine PR to be merged first as the branches are different names.

### CODE REVIEW

**Comment by Martian42** [comment]
@peterjamesnugent sorry, I'm struggling to use the Excel linked for testing. Can you also include the file "37649 - 2023-06-26 1500 - Preliminary - 1 GEL\37649 - 2023-06-26 1500 - Preliminary - 1 GEL.ags"? I can then copy the Excel file offline and test out the new functions.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance

**Review by Martian42 — APPROVED** [review]
Tested functionality with test script using an .ags file with empty GEOL. All option works as intented.

**Pull request merged**
