### PR TITLE
Store text in qualifier if it's not empty

### LINKED ISSUE #20: Add any ERES_RTXT values to InterpretedQualifier e.g. No Abestos Detected

### LINKED ISSUE #22: Unit value was not being stored with ERES_RTXT so was not being referenced for conversions
#### Description:

When changing from ERES_RVAL to ERES_RTXT the unit heading in the dicitionary was not updated.

#### Steps to reproduce:

Pull Borehole and check `ContaminantSample.Result`.

#### Expected behaviour:

Unit conversion to take place.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #20 
Closes #22 

### Test files

https://burohappold.sharepoint.com/:u:/s/BHoM/EXTqPS5noR9FkHJcowtmoksBKTdIQzZ4wiNxv1koKKiMow?e=aDQDEE

### Changelog

- Store text such as "No Abestos Detected" in `InterpretedQualifier` field as it's useful for post processing;
- Fixed a bug whereby the units for the `ContaminantSample` was not being properly captured.

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by jtrainor1 — DISMISSED** [review]
Works as intended. I am able to review contaminant data and see the qualifiers ahead of the numerical result. These can then be viewed with the results to understand the correct information, so I can see it's <1 and not just 1.

**Comment by peterjamesnugent** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by jtrainor1 — APPROVED** [review]
Text in qualifier is stored as intended.

**Comment by peterjamesnugent** [comment]
@BHoMBot check copyright-compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
