### PR TITLE
Add AGS_Toolkit to Alpha Installer

### LINKED ISSUE #17: Add AGS_Toolkit in to the Alpha

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #17

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check ready-to-merge

**Comment by adecler** [comment]
@BHoMBot check required

**Review by michaelhoehn — APPROVED** [review]
Happy to approve! Branch protection CI updates have been applied as well.

**Pull request merged**
